version: '2'
services:
  redis:
    image: redis:7-alpine
    ports:
    - 6379:6379
  mysql:
    image: mariadb:10
    ports:
    - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: gamma
      MARIADB_USER: gamma
      MARIADB_PASSWORD: 1234
  # optional: view tracing
  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./ext/tempo-local.yaml:/etc/tempo.yaml
      - gamma-tempo-data:/tmp/tempo
    ports:
      - "3200:3200"   # tempo
      - "4317:4317"  # otlp grpc

  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    volumes:
      - ./ext/prometheus-local.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:9.3.0
    volumes:
      - ./ext/grafana-local.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"

volumes:
  gamma-tempo-data:
